# Generated by Django 3.0.8 on 2020-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.TextField()),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('year', models.TextField()),
                ('branch', models.TextField()),
                ('section', models.TextField()),
                ('password1', models.TextField()),
                ('password2', models.TextField()),
            ],
        ),
    ]
