# Generated by Django 3.0.8 on 2020-08-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='register',
            name='password2',
        ),
    ]
