# Generated by Django 3.0.8 on 2020-09-16 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.CreateModel(
            name='Eregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('cgpa', models.TextField()),
                ('baclogs', models.TextField()),
                ('year', models.TextField()),
                ('branch', models.TextField()),
                ('section', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
