# Generated by Django 3.0.8 on 2020-09-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200916_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eregister',
            old_name='baclogs',
            new_name='backlogs',
        ),
    ]
