# Generated by Django 3.0.8 on 2020-09-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200919_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eregister',
            name='cgpa',
            field=models.BooleanField(),
        ),
    ]
