# Generated by Django 3.0.8 on 2020-09-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200919_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eregister',
            old_name='cgpa',
            new_name='grade',
        ),
    ]
