# Generated by Django 3.0.8 on 2020-09-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_addevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='eregister',
            name='event',
            field=models.TextField(default='basic'),
            preserve_default=False,
        ),
    ]
