# Generated by Django 3.0.8 on 2020-10-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_eregister_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.TextField()),
                ('name', models.TextField()),
                ('eventname', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
